# Generated by Django 4.0.6 on 2022-07-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categoria_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
